name       : python-xapp
version    : 2.2.1
release    : 10
source     :
    - https://github.com/linuxmint/python3-xapp/archive/refs/tags/2.2.1.tar.gz : 6dcba34e3de89bb3dfb1237a571f72a99b19fa73728205c38e38e9c6c945613d
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
