name       : python-xapp
version    : 1.4.0
release    : 1
source     :
    - https://github.com/linuxmint/python-xapp/archive/1.4.0.tar.gz : 71ab0ee87df2c6902b36c66c1764b47f558ce3dd1a95b6435a0e65cee8d7eb26
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
install    : |
    %python_install
