name       : python-xapp
version    : 1.8.1
release    : 3
source     :
    - https://github.com/linuxmint/python-xapp/archive/1.8.1.tar.gz : f407edf5db6a30fcdec26a24addc86dc7b7ed891890fb128dd36675a95434355
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
runddeps   :
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
