name       : python-xapp
version    : 2.4.0
release    : 13
source     :
    - https://github.com/linuxmint/python3-xapp/archive/refs/tags/2.4.0.tar.gz : fb907ffb0d777e13f0235eaed3e7dd4d2ecf9e66d9dab578d78af115e817c10e
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
setup      : |
    %meson_configure
build    : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
