name       : python-xapp
version    : 2.2.0
release    : 8
source     :
    - https://github.com/linuxmint/python3-xapp/archive/2.2.0.tar.gz : 481755d3d89f422e6064c5844b4f5a1f31e324b9214800a41b3618e81c4f2421
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
