name       : python-xapp
version    : 1.6.0
release    : 2
source     :
    - https://github.com/linuxmint/python-xapp/archive/1.6.0.tar.gz : 0de55525b12166d80895ef14b0ba4583b1cd8c23d9262357a18d5f47cf7254df
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
runddeps   :
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
