name       : python-xapp
version    : 2.0.2
release    : 7
source     :
    - https://github.com/linuxmint/python3-xapp/archive/2.0.2.tar.gz : 4f61dde32c7aec5ab2c819e968a2bf0136c9eddcc1356461d516aff40930159f
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
