name       : python-xapp
version    : 2.4.1
release    : 14
source     :
    - https://github.com/linuxmint/python3-xapp/archive/refs/tags/2.4.1.tar.gz : d994f922a9816c71d9b565f4b2552cba4ca33011efb1203fb8199d9b2d0d7f3d
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
