name       : python-xapp
version    : 2.2.2
release    : 12
source     :
    - https://github.com/linuxmint/python3-xapp/archive/refs/tags/2.2.2.tar.gz : 644b44ee97616096d74fc8a4a104453154fdc1c904679077b13b2e0b9c1b3c21
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
rundeps    :
    - python-gobject
    - python-psutil
build      : |
    %python3_setup
install    : |
    %python3_install
