name       : python-xapp
version    : 2.0.1
release    : 5
source     :
    - https://github.com/linuxmint/python3-xapp/archive/2.0.1.tar.gz : ed32ec4e81bfcc1de1d5f33dcc0a3dcfec9583b74a2af22d4c3188cec6ea7f4c
homepage   : https://github.com/linuxmint/python3-xapp
license    : LGPL-2.0-or-later
component  : programming.python
summary    : Xapp Python library
description: |
    The Xapp Python library.
runddeps   :
    - python-psutil
    - python3-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
